### ISSUE TITLE
'Server is restarting' PM causes crash

### ISSUE THREAD

**Issue by ArkUmbra** [MajeurAndroid/Android-Unofficial-Showdown-Client#9]
This happened before I merged your changes into my branch, so it's possible you've already seen this. If so, please just ignore/close this issue.

Today when trying to search for a battle, the Showdown battle servers were due to restart. When I searched for a battle, it resulted in a crash.

This is the message which caused it
`|pm|&| ArkUmbraTest3|/raw <div class="broadcast-red"><b>The server is restarting soon.</b><br />Please finish your battles quickly. No new battles can be started until the server resets in a few minutes.</div>`

And here is some log info

```
I/WebSocket[SEND]: |/utm null
    |/search gen8randombattle
I/WebSocket[RECEIVE]: |popup|The server is restarting. Battles will be available again in a few minutes.
I/WebSocket[SEND]: |/utm null
I/WebSocket[SEND]: |/search gen8randombattle
I/WebSocket[RECEIVE]: |popup|The server is restarting. Battles will be available again in a few minutes.
I/WebSocket[RECEIVE]: |pm|&| ArkUmbraTest3|/raw <div class="broadcast-red"><b>The server is restarting soon.</b><br />Please finish your battles quickly. No new battles can be started until the server resets in a few minutes.</div>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.majeur.psclient, PID: 9329
    java.util.NoSuchElementException: Sequence contains no element matching the predicate.
        at com.majeur.psclient.widget.PrivateMessagesOverviewWidget.updateViewForEntry(PrivateMessagesOverviewWidget.kt:161)
        at com.majeur.psclient.widget.PrivateMessagesOverviewWidget.incrementPmCount(PrivateMessagesOverviewWidget.kt:37)
        at com.majeur.psclient.ui.HomeFragment.onNewPrivateMessage(HomeFragment.kt:640)
        at com.majeur.psclient.service.observer.GlobalMessageObserver.onNewPrivateMessage(GlobalMessageObserver.kt:274)
        at com.majeur.psclient.service.observer.GlobalMessageObserver.handlePm(GlobalMessageObserver.kt:234)
        at com.majeur.psclient.service.observer.GlobalMessageObserver.onMessage(GlobalMessageObserver.kt:55)
        at com.majeur.psclient.service.observer.AbsMessageObserver.postMessage(AbsMessageObserver.kt:25)
        at com.majeur.psclient.service.observer.AbsMessageObserver.postMessage$default(AbsMessageObserver.kt:24)
        at com.majeur.psclient.service.ShowdownService.dispatchMessage(ShowdownService.kt:178)
        at com.majeur.psclient.service.ShowdownService.dispatchServerData(ShowdownService.kt:164)
        at com.majeur.psclient.service.ShowdownService.processServerData(ShowdownService.kt:158)
        at com.majeur.psclient.service.ShowdownService.access$processServerData(ShowdownService.kt:20)
        at com.majeur.psclient.service.ShowdownService$webSocketListener$1$onMessage$1.run(ShowdownService.kt:201)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 9329 SIG: 9
```

**Comment by MajeurAndroid** [comment]
Yes the crash has been fixed here c2d263c.
But the behaviour of such pms has to be implemented. (Pms coming from special users such as '&' in this case, but also '~' and other I guess...)
